// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Diary struct {
	ID       string  `json:"id"`
	Text     *string `json:"text"`
	Imageurl string  `json:"imageurl"`
	Userid   string  `json:"userid"`
}

type NewDiary struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
