// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Diary struct {
	Diaryid   string  `json:"Diaryid"`
	Word      *string `json:"Word"`
	Imageurl  string  `json:"Imageurl"`
	Userid    string  `json:"Userid"`
	CreatedAt string  `json:"CreatedAt"`
	UpdatedAt string  `json:"UpdatedAt"`
}

type Me struct {
	User     *User        `json:"User"`
	Diary    []*Diary     `json:"Diary"`
	Followee []*UserDiary `json:"Followee"`
	Follower []*UserDiary `json:"Follower"`
}

type NewDiary struct {
	Word     *string `json:"Word"`
	Userid   string  `json:"Userid"`
	Imageurl string  `json:"Imageurl"`
}

type NewFollow struct {
	Followee string `json:"Followee"`
	Follower string `json:"Follower"`
}

type NewUser struct {
	Userid string `json:"Userid"`
	Name   string `json:"Name"`
}

type User struct {
	Userid string `json:"Userid"`
	Name   string `json:"Name"`
}

type UserDiary struct {
	User  *User    `json:"User"`
	Diary []*Diary `json:"Diary"`
}
